private ["_missName","_coords","_crash","_crate"];
_missName	=	"Падение вертолета";
_coords		=	call DZMSFindPos;
[nil,nil,rTitleText,"Разбился вертолет преступной группировки! Проверь свою карту!", "PLAIN",10] call RE;
[_coords,_missName] ExecVM DZMSAddMinMarker;
_crash	=	createVehicle ["UH60Wreck_DZ", _coords,[], 0, "CAN_COLLIDE"];
[_crash] call DZMSProtectObj;
_crate	=	createVehicle ["USLaunchersBox",[(_coords select 0) - 6, _coords select 1,0],[], 0, "CAN_COLLIDE"];
[_crate,"weapons"] ExecVM DZMSBoxSetup;
[_crate] call DZMSProtectObj;
[_coords,3,1] ExecVM DZMSAISpawn;
sleep 1;
[_coords,3,1] ExecVM DZMSAISpawn;
sleep 1;
[_coords,3,1] ExecVM DZMSAISpawn;
sleep 1;
waitUntil{{isPlayer _x && _x distance _coords <= 30  } count playableunits > 0}; 
[nil,nil,rTitleText,"Место падения вертолета перешло под контроль выживших!", "PLAIN",6] call RE;
diag_log format["[DZMS]: Минор миссия SM4 завершена."];
deleteMarker "DZMSMinMarker";
deleteMarker "DZMSMinDot";
DZMSMinDone = true;