private ["_missName","_coords","_crash","_crate","_crate1","_crate2"];
_missName	=	"Грузовик преступников";
_coords		=	call DZMSFindPos;
[nil,nil,rTitleText,"Грузовик с вооружением, для преступной группы попал в аварию! Проверь свою карту!", "PLAIN",10] call RE;
[_coords,_missName] ExecVM DZMSAddMinMarker;
_crash	=	createVehicle ["UralWreck",_coords,[], 0, "CAN_COLLIDE"];
[_crash] call DZMSProtectObj;
_crate	=	createVehicle ["USLaunchersBox",[(_coords select 0) + 3, _coords select 1,0],[], 0, "CAN_COLLIDE"];
[_crate,"weapons"] ExecVM DZMSBoxSetup;
[_crate] call DZMSProtectObj;
_crate1	=	createVehicle ["USLaunchersBox",[(_coords select 0) - 3, _coords select 1,0],[], 0, "CAN_COLLIDE"];
[_crate1,"weapons"] ExecVM DZMSBoxSetup;
[_crate1] call DZMSProtectObj;
_crate2	=	createVehicle ["RULaunchersBox",[(_coords select 0) - 6, _coords select 1,0],[], 0, "CAN_COLLIDE"];
[_crate2,"weapons"] ExecVM DZMSBoxSetup;
[_crate2] call DZMSProtectObj;
[_coords,3,0] ExecVM DZMSAISpawn;
sleep 1;
[_coords,3,0] ExecVM DZMSAISpawn;
sleep 1;
[_coords,3,0] ExecVM DZMSAISpawn;
sleep 1;
[_coords,3,0] ExecVM DZMSAISpawn;
sleep 1;
waitUntil{{isPlayer _x && _x distance _coords <= 30 } count playableunits > 0}; 
[nil,nil,rTitleText,"Грузовик с вооружением перешел под контроль выживших!", "PLAIN",6] call RE;
diag_log format["[DZMS]: Минор миссия SM6 завершена."];
deleteMarker "DZMSMinMarker";
deleteMarker "DZMSMinDot";
DZMSMinDone	=	true;