private ["_missName","_coords","_vehicle","_vehicle1","_crate"];
_missName	=	"Вооружене NATO";
_coords		=	call DZMSFindPos;
[nil,nil,rTitleText,"Преступники захватили склад с оружием NATO!", "PLAIN",10] call RE;
[_coords,_missname] ExecVM DZMSAddMajMarker;
_crate	=	createVehicle ["Land_CamoNetB_NATO",[(_coords select 0) - 0.0649, (_coords select 1) + 0.6025,0],[], 0, "CAN_COLLIDE"];
[_crate] call DZMSProtectObj;
_vehicle	=	createVehicle ["SUV_TK_CIV_EP1",[(_coords select 0) + 10.0303, (_coords select 1) - 12.2979,10],[], 0, "CAN_COLLIDE"];
_vehicle1	=	createVehicle ["Ural_INS",[(_coords select 0) - 4869.2983, (_coords select 1) - 9663.6406,10],[], 0, "CAN_COLLIDE"];
[_vehicle] call DZMSSetupVehicle;
[_vehicle1] call DZMSSetupVehicle;
_crate	=	createVehicle ["USVehicleBox",_coords,[], 0, "CAN_COLLIDE"];
[_crate,"weapons"] ExecVM DZMSBoxSetup;
[_crate] call DZMSProtectObj;
_crate	=	createVehicle ["AmmoBoxSmall_556",[(_coords select 0) - 3.7251,(_coords select 1) - 2.3614, 0],[], 0, "CAN_COLLIDE"];
[_crate] call DZMSProtectObj;
_crate	=	createVehicle ["AmmoBoxSmall_762",[(_coords select 0) - 3.4346, 0, 0],[], 0, "CAN_COLLIDE"];
[_crate] call DZMSProtectObj;
_crate	=	createVehicle ["AmmoBoxSmall_556",[(_coords select 0) + 4.0996,(_coords select 1) + 3.9072, 0],[], 0, "CAN_COLLIDE"];
[_crate] call DZMSProtectObj;
[[(_coords select 0) + 0.0352,(_coords select 1) - 6.8799, 0],6,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) + 0.0352,(_coords select 1) - 6.8799, 0],6,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) + 0.0352,(_coords select 1) - 6.8799, 0],4,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) + 0.0352,(_coords select 1) - 6.8799, 0],4,1] ExecVM DZMSAISpawn;
sleep 5;
waitUntil{ {isPlayer _x && _x distance _coords <= 30 } count playableunits > 0 }; 
[_vehicle] ExecVM DZMSSaveVeh;
[_vehicle1] ExecVM DZMSSaveVeh;
[nil,nil,rTitleText,"Выжившие получили контроль над складом с оружием!", "PLAIN",6] call RE;
diag_log format["[DZMS]: Мажор миссия SM1 завершена."];
deleteMarker "DZMSMajMarker";
deleteMarker "DZMSMajDot";
DZMSMajDone = true;