private ["_missName","_coords","_ranChopper","_chopper","_truck","_trash","_trash2","_crate","_crate2"];
_missName	=	"Вертолет с припасами";
_coords		=	call DZMSFindPos;
[nil,nil,rTitleText,"Замечен вертолет с припасами!\nОстанови преступников и захвати груз!", "PLAIN",10] call RE;
[_coords,_missname] ExecVM DZMSAddMajMarker;
_ranChopper	=	["UH1H_DZE","Mi17_DZE"] call BIS_fnc_selectRandom;
_chopper		=	createVehicle [_ranChopper,_coords,[], 0, "NONE"];
[_chopper] call DZMSSetupVehicle;
_chopper setDir -36.279881;
_truck	=	createVehicle ["HMMWV_DZ",[(_coords select 0) - 8.7802,(_coords select 1) + 6.874,0],[], 0, "CAN_COLLIDE"];
[_truck] call DZMSSetupVehicle;
_trash	=	createVehicle ["Body1",[(_coords select 0) - 3.0185,(_coords select 1) - 0.084,0],[], 0, "CAN_COLLIDE"];
_trash2	=	createVehicle ["Body2",[(_coords select 0) + 1.9248,(_coords select 1) + 2.1201,0],[], 0, "CAN_COLLIDE"];
[_trash] call DZMSProtectObj;
[_trash2] call DZMSProtectObj;
_crate	=	createVehicle ["USLaunchersBox",[(_coords select 0) - 6.1718,(_coords select 1) + 0.6426,0],[], 0, "CAN_COLLIDE"];
[_crate,"weapons"] ExecVM DZMSBoxSetup;
[_crate] call DZMSProtectObj;
_crate2	=	createVehicle ["USLaunchersBox",[(_coords select 0) - 2.9824,(_coords select 1) + 4.0,0],[], 90, "CAN_COLLIDE"];
[_crate2,"weapons"] ExecVM DZMSBoxSetup;
[_crate2] call DZMSProtectObj;
[[(_coords select 0) - 8.4614,(_coords select 1) - 5.0527,0],6,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) - 8.4614,(_coords select 1) - 5.0527,0],4,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) + 7.5337,(_coords select 1) + 4.2656,0],4,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) + 7.5337,(_coords select 1) + 4.2656,0],4,1] ExecVM DZMSAISpawn;
sleep 5;
waitUntil{{isPlayer _x && _x distance _coords <= 30  } count playableunits > 0}; 
[_chopper] ExecVM DZMSSaveVeh;
[_truck] ExecVM DZMSSaveVeh;
[nil,nil,rTitleText,"Вертолет с припасами перешел под контроль выживших!", "PLAIN",6] call RE;
diag_log format["[DZMS]: Мажор миссия SM4 завершена."];
deleteMarker "DZMSMajMarker";
deleteMarker "DZMSMajDot";
DZMSMajDone	=	true;