private ["_missName","_coords","_net","_vehicle","_vehicle1","_crate"];
_missName	=	"Мед. центр";
_coords		=	call DZMSFindPos;
[nil,nil,rTitleText,"Бандиты захватили уцелевший мед. центр!", "PLAIN",10] call RE;
[_coords,_missname] ExecVM DZMSAddMajMarker;
_net	=	createVehicle ["Land_CamoNetB_NATO",[(_coords select 0) - 0.0649, (_coords select 1) + 0.6025,0],[], 0, "CAN_COLLIDE"];
[_net] call DZMSProtectObj;
_vehicle	=	createVehicle ["SUV_TK_CIV_EP1",[(_coords select 0) + 10.0303, (_coords select 1) - 12.2979,10],[], 0, "CAN_COLLIDE"];
_vehicle1	=	createVehicle ["Ural_INS",[(_coords select 0) - 4869.2983, (_coords select 1) - 9663.6406,10],[], 0, "CAN_COLLIDE"];
[_vehicle] call DZMSSetupVehicle;
[_vehicle1] call DZMSSetupVehicle;
_crate	=	createVehicle ["USVehicleBox",_coords,[], 0, "CAN_COLLIDE"];
_crate1	=	createVehicle ["MedBox0",[(_coords select 0) - 3.7251,(_coords select 1) - 2.3614, 0],[], 0, "CAN_COLLIDE"];
_crate2	=	createVehicle ["MedBox0",[(_coords select 0) - 3.4346, 0, 0],[], 0, "CAN_COLLIDE"];
_crate3	=	createVehicle ["MedBox0",[(_coords select 0) + 4.0996,(_coords select 1) + 3.9072, 0],[], 0, "CAN_COLLIDE"];
[_crate,"medical"] ExecVM DZMSBoxSetup;
[_crate] call DZMSProtectObj;
[_crate1] call DZMSProtectObj;
[_crate2] call DZMSProtectObj;
[_crate3] call DZMSProtectObj;
[[(_coords select 0) + 0.0352,(_coords select 1) - 6.8799, 0],6,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) + 0.0352,(_coords select 1) - 6.8799, 0],6,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) + 0.0352,(_coords select 1) - 6.8799, 0],4,1] ExecVM DZMSAISpawn;
sleep 5;
[[(_coords select 0) + 0.0352,(_coords select 1) - 6.8799, 0],4,1] ExecVM DZMSAISpawn;
sleep 5;
waitUntil{ {isPlayer _x && _x distance _coords <= 30 } count playableunits > 0 }; 
[_vehicle] ExecVM DZMSSaveVeh;
[_vehicle1] ExecVM DZMSSaveVeh;
[nil,nil,rTitleText,"Мед. центр перешел под контроль выживших!", "PLAIN",6] call RE;
diag_log format["[DZMS]: Мажор миссия SM6 завершена."];
deleteMarker "DZMSMajMarker";
deleteMarker "DZMSMajDot";
DZMSMajDone	=	true;